// build-view.mjs — the build view mod's PURE half (build-visualization-claude-mods S4, D3).
//
// The hook module (./index.ts) may only call `$.noun.event(...)` at a call site — the runtime rejects a
// module that passes `$` around — so everything that can be decided without `$` lives here, where
// `node --test` can reach it. The mod itself is then: read the key, ask this module whether to refresh,
// run `scripts/build-state.mjs`, hand the text to `$.ui.status`. No markdown parsing, no logic of its own.

/**
 * What `git rev-parse HEAD --abbrev-ref HEAD --show-toplevel` says: the cache key (branch@sha) and the
 * repository ROOT. The root matters — a session started in a subdirectory would otherwise run
 * `scripts/build-state.mjs` relative to that subdirectory and never find it.
 */
export function repoFactsFrom(stdout, exitCode = 0) {
  if (exitCode !== 0) return { key: null, root: null };
  const [sha = '', branch = '', root = ''] = String(stdout || '')
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean);
  return { key: sha && branch ? `${branch}@${sha}` : null, root: root || null };
}

// A Roadmap/ write changes no git ref, so a key alone would serve a stale view until the next commit.
// Stat-ing the whole tree every turn is the cost the cache exists to avoid (860+ docs in the largest
// consumer), so a refresh also happens when the cached view is older than this. A doc edit therefore
// shows up within 15s; a branch change or a commit shows up immediately.
export const MAX_AGE_MS = 15_000;

/**
 * Refresh when there is no usable entry, the branch/HEAD moved, or the view aged out.
 *
 * A FAILED resolve is a usable entry: `text: null` is cached like any other answer, so a project that
 * has the plugin but not `scripts/build-state.mjs` re-tries once every MAX_AGE_MS instead of spawning a
 * doomed `node` on every single turn (the fresh reviewer's finding on #32). `key: null` — no git, or a
 * `git rev-parse` that failed — is the one case with nothing to key on, and it refreshes every turn by
 * design: there is no way to know that anything is still true.
 */
export function shouldRefresh(cached, key, now = Date.now()) {
  if (!key) return true;
  if (!cached || cached.key !== key) return true;
  const resolved = typeof cached.text === 'string' || cached.text === null;
  if (!resolved || !('text' in cached)) return true;
  return !(Number.isFinite(cached.at) && now - cached.at < MAX_AGE_MS);
}

/**
 * The status text for one `build-state.mjs --json` run: its OWN `lines`, joined — never re-derived here
 * (D3). A non-zero exit, unparseable output or a missing `lines` array renders nothing at all: a build
 * view that invents a line is worse than no build view.
 */
export function statusTextFrom(stdout, exitCode = 0) {
  if (exitCode !== 0) return null;
  try {
    const state = JSON.parse(String(stdout));
    return Array.isArray(state.lines) && state.lines.length ? state.lines.join('\n') : null;
  } catch {
    return null;
  }
}

/**
 * The resolver bundled beside this file (`hooks/vendor/`, generated by skills/scripts/render-hook-vendor.mjs).
 * Located from this module's own URL — probed live in a function-hooks module (distribute-what-we-use S2.2):
 * `import.meta.url` is the plugin's installed directory, and `$.process.run` can execute a file there.
 * Decoded by hand so this file keeps its no-import shape; the drive-letter strip covers a Windows install.
 */
export const VENDOR_BUILD_STATE = decodeURIComponent(
  new URL('./vendor/build-state.mjs', import.meta.url).pathname
).replace(/^\/([A-Za-z]:\/)/, '$1');

/**
 * The command the hook runs. ALWAYS the bundled resolver — never `<repo>/scripts/build-state.mjs`, whether
 * or not the open repo has one (D5). The hook is automatic: it runs on every turn in whatever repo the user
 * opens, so it must never execute a file that repo supplies. The repo is only ever READ, via `--repo-root`.
 */
export function buildStateArgv(root, script = VENDOR_BUILD_STATE) {
  return ['node', script, '--json', '--offline', '--repo-root', root || '.'];
}

// ── The usage refresh (finops S1.3, D24) ─────────────────────────────────────────────────────────────────
// The Spend row reads a summary file; `session.measure` keeps it fresh by running the BUNDLED epic-actuals.mjs (never
// the open repo's — same rule as the resolver) at most once per USAGE_REFRESH_MS, with a timeout. A refresh is local
// file reads only; it never touches the network (the opt-in engine push is a separate, later switch).
export const VENDOR_EPIC_ACTUALS = decodeURIComponent(
  new URL('./vendor/epic-actuals.mjs', import.meta.url).pathname
).replace(/^\/([A-Za-z]:\/)/, '$1');
export const USAGE_REFRESH_MS = 60_000;
export const USAGE_TIMEOUT_MS = 10_000;

/** The command the mod runs to refresh the usage index. The repo is only READ, via `--repo-root`. */
export function epicActualsArgv(root, script = VENDOR_EPIC_ACTUALS) {
  return ['node', script, '--refresh', '--repo-root', root || '.'];
}

/** Refresh when there is a repo and the last attempt (ok or not) is older than USAGE_REFRESH_MS. */
export function shouldRefreshUsage(lastAt, root, now = Date.now()) {
  if (!root) return false;
  return !(Number.isFinite(lastAt) && now - lastAt < USAGE_REFRESH_MS);
}

// ── The band's rows (fix/build-view-band) ────────────────────────────────────────────────────────────
// The view used to go to `$.ui.status`, a ONE-line status row: the resolver's newlines were drawn as U+FFFD
// and everything past the terminal's width was cut off. It is now drawn as a band above the prompt, one
// wrapped row per resolver line. These rows only DECORATE the resolver's own lines — a glyph and a tone per
// label — and never add or drop a fact (D3): every row's `label` + `value` is its source line, trimmed.

const LABEL_GLYPHS = {
  Epic: '◆',
  Feature: '◆',
  Bug: '◆',
  Spike: '◆',
  Chore: '◆',
  Story: '▸',
  Seed: '❧',
  Progress: '▰',
  Spend: '$', // finops S1.3
  Status: '●',
  Open: '○',
  Also: '↳',
  Board: '▦',
};

/** A tone for a status/phase word — a colour hint only; the word itself is always shown as written. */
export function toneOf(value) {
  const v = String(value || '').toLowerCase();
  if (/^unknown|blocked|failed|stale/.test(v)) return 'bad';
  if (/shipped|done|live|merged|complete/.test(v)) return 'good';
  if (/^qa\b|verifying|review|smoke/.test(v)) return 'info';
  if (/building|in progress|groom|planning|ready/.test(v)) return 'busy';
  return 'plain';
}

/** `Story 2 of 5` → `{ done: 1, total: 5 }` (the current story is not done yet); anything else → null. */
export function progressOf(value) {
  const m = /Story (\d+) of (\d+)/.exec(String(value || ''));
  if (!m) return null;
  const total = Number(m[2]);
  const done = Math.max(0, Math.min(total, Number(m[1]) - 1));
  return total > 0 ? { done, total } : null;
}

/**
 * The view text (the resolver's lines, joined) as band rows:
 *   heading — the first line (`Currently building`, `No epic in flight — …`)
 *   field   — `  <Label>   <value>` (the resolver pads labels to 9); `main` + `meta` split the value at the
 *             resolver's four-space gap, `risk` is the meta's `risk X` word when there is one
 *   note    — a continuation line (the user story), indented under the value
 * An empty or null text gives no rows, so the band draws nothing.
 */
export function bandRowsFrom(text) {
  if (typeof text !== 'string' || !text.trim()) return [];
  return text.split('\n').map((line, i) => {
    if (i === 0) {
      const idle = /^No epic in flight/.test(line);
      return { kind: 'heading', glyph: idle ? '◇' : '◆', value: line, tone: idle ? 'plain' : 'busy' };
    }
    const field = /^ {2}([A-Z][A-Za-z]*) +(\S.*)$/.exec(line);
    if (field && field[1] in LABEL_GLYPHS) {
      const [, label, value] = field;
      const tone = label === 'Status' || label === 'Open' ? toneOf(label === 'Open' ? value.split(' · ')[1] : value) : 'plain';
      // `title    area · risk X`: the resolver separates the meta with four spaces; drawn dim beside it.
      const [main, ...rest] = value.split(/ {4,}/);
      const meta = rest.join('  ') || null;
      const risk = /risk (\w+)/.exec(meta || '')?.[1] || null;
      return { kind: 'field', glyph: LABEL_GLYPHS[label], label, value, main, meta, risk, tone };
    }
    return { kind: 'note', glyph: '│', value: line.trim(), tone: 'plain' };
  });
}

// ── Engines without `$.state` (fix/build-view-no-state-at-start) ────────────────────────────────────────
// The band reads the view from `$.state`, which the engine only has from some version after 2.1.278 (the CI
// pin): 2.1.278 has no `state` noun at all, so `$.state.get` throws a TypeError on every draw. A render hook
// must never throw, so every `$.state` call goes through `attempt`. It is pure — the hook passes a thunk that
// spells `$` at its own call site — so the guard is testable here, where removing it turns a test red.

/**
 * Runs `fn` and resolves its result; when it throws (synchronously, as a missing noun does) or rejects,
 * calls `onFail(err)` and resolves `fallback` instead. It never throws.
 */
export async function attempt(fn, onFail = () => {}, fallback = null) {
  try {
    return await fn();
  } catch (err) {
    try {
      onFail(err);
    } catch {
      /* a failing logger must not undo the guard */
    }
    return fallback;
  }
}
