// build-view.mjs — the build view mod's PURE half (build-visualization-claude-mods S4, D3).
//
// The hook module (./index.ts) may only call `$.noun.event(...)` at a call site — the runtime rejects a
// module that passes `$` around — so everything that can be decided without `$` lives here, where
// `node --test` can reach it. The mod itself is then: read the key, ask this module whether to refresh,
// run `scripts/build-state.mjs`, hand the text to `$.ui.status`. No markdown parsing, no logic of its own.

/**
 * What `git rev-parse HEAD --abbrev-ref HEAD --show-toplevel` says: the cache key (branch@sha) and the
 * repository ROOT. The root matters — a session started in a subdirectory would otherwise run
 * `scripts/build-state.mjs` relative to that subdirectory and never find it.
 */
export function repoFactsFrom(stdout, exitCode = 0) {
  if (exitCode !== 0) return { key: null, root: null };
  const [sha = '', branch = '', root = ''] = String(stdout || '')
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean);
  return { key: sha && branch ? `${branch}@${sha}` : null, root: root || null };
}

// The key (live-build-view D2) covers what moves a view: every worktree's HEAD + branch and the newest Roadmap/ mtime.
// MAX_AGE_MS is now only a backstop for what the key cannot see (the session journal's refs) — it used to be 15 s,
// when a doc edit was invisible to the key; with a 30 s tick that age would re-resolve on every tick for nothing.
export const MAX_AGE_MS = 300_000;
/**
 * Refresh when there is no usable entry, the branch/HEAD moved, or the view aged out.
 *
 * A FAILED resolve is a usable entry: `text: null` is cached like any other answer, so a project that
 * has the plugin but not `scripts/build-state.mjs` re-tries once every MAX_AGE_MS instead of spawning a
 * doomed `node` on every single turn (the fresh reviewer's finding on #32). `key: null` — no git, or a
 * `git rev-parse` that failed — is the one case with nothing to key on, and it refreshes every turn by
 * design: there is no way to know that anything is still true.
 */
export function shouldRefresh(cached, key, now = Date.now()) {
  if (!key) return true;
  if (!cached || cached.key !== key) return true;
  const resolved = typeof cached.text === 'string' || cached.text === null;
  if (!resolved || !('text' in cached)) return true;
  return !(Number.isFinite(cached.at) && now - cached.at < MAX_AGE_MS);
}

/**
 * The status text for one `build-state.mjs --json` run: its OWN `lines`, joined — never re-derived here
 * (D3). A non-zero exit, unparseable output or a missing `lines` array renders nothing at all: a build
 * view that invents a line is worse than no build view.
 */
export function statusTextFrom(stdout, exitCode = 0) {
  if (exitCode !== 0) return null;
  try {
    const state = JSON.parse(String(stdout));
    return Array.isArray(state.lines) && state.lines.length ? state.lines.join('\n') : null;
  } catch {
    return null;
  }
}

/**
 * The resolver bundled beside this file (`hooks/vendor/`, generated by skills/scripts/render-hook-vendor.mjs).
 * Located from this module's own URL — probed live in a function-hooks module (distribute-what-we-use S2.2):
 * `import.meta.url` is the plugin's installed directory, and `$.process.run` can execute a file there.
 * Decoded by hand so this file keeps its no-import shape; the drive-letter strip covers a Windows install.
 */
export const VENDOR_BUILD_STATE = decodeURIComponent(
  new URL('./vendor/build-state.mjs', import.meta.url).pathname
).replace(/^\/([A-Za-z]:\/)/, '$1');

/**
 * The command the hook runs. ALWAYS the bundled resolver — never `<repo>/scripts/build-state.mjs`, whether
 * or not the open repo has one (D5). The hook is automatic: it runs on every turn in whatever repo the user
 * opens, so it must never execute a file that repo supplies. The repo is only ever READ, via `--repo-root`.
 */
export function buildStateArgv(root, script = VENDOR_BUILD_STATE, { offline = true } = {}) {
  return ['node', script, '--json', ...(offline ? ['--offline'] : []), '--repo-root', root || '.'];
}

// ── The usage refresh (finops S1.3, D24) ─────────────────────────────────────────────────────────────────
// The Spend row reads a summary file; `session.measure` keeps it fresh by running the BUNDLED epic-actuals.mjs (never
// the open repo's — same rule as the resolver) at most once per USAGE_REFRESH_MS, with a timeout. A refresh is local
// file reads — plus, ONLY when the project opted in with `spend.telemetry: on`, the usage push to its engine (finops
// S3.1, D24): after a complete scan, within 5 s, at most every 10 minutes.
export const VENDOR_EPIC_ACTUALS = decodeURIComponent(
  new URL('./vendor/epic-actuals.mjs', import.meta.url).pathname
).replace(/^\/([A-Za-z]:\/)/, '$1');
export const USAGE_REFRESH_MS = 60_000;
export const USAGE_TIMEOUT_MS = 15_000; // a ≤6 s scan + the opt-in push's ≤5 s budget (finops D24)

/** The command the mod runs to refresh the usage index. The repo is only READ, via `--repo-root`. */
export function epicActualsArgv(root, script = VENDOR_EPIC_ACTUALS) {
  return ['node', script, '--refresh', '--repo-root', root || '.'];
}

/** Refresh when there is a repo and the last attempt (ok or not) is older than USAGE_REFRESH_MS. */
export function shouldRefreshUsage(lastAt, root, now = Date.now()) {
  if (!root) return false;
  return !(Number.isFinite(lastAt) && now - lastAt < USAGE_REFRESH_MS);
}

// ── The band's rows (fix/build-view-band) ────────────────────────────────────────────────────────────
// The view used to go to `$.ui.status`, a ONE-line status row: the resolver's newlines were drawn as U+FFFD
// and everything past the terminal's width was cut off. It is now drawn as a band above the prompt, one
// wrapped row per resolver line. These rows only DECORATE the resolver's own lines — a glyph and a tone per
// label — and never add or drop a fact (D3): every row's `label` + `value` is its source line, trimmed.

const LABEL_GLYPHS = {
  Epic: '◆',
  Feature: '◆',
  Bug: '◆',
  Spike: '◆',
  Chore: '◆',
  Story: '▸',
  Seed: '❧',
  Progress: '▰',
  Spend: '$', // finops S1.3
  Status: '●',
  Open: '○',
  Also: '↳',
  Board: '▦',
  Plugin: '⬆', // live-build-view D5 — the installed plugin is older than the published one
};

/** A tone for a status/phase word — a colour hint only; the word itself is always shown as written. */
export function toneOf(value) {
  const v = String(value || '').toLowerCase();
  if (/^unknown|blocked|failed|stale/.test(v)) return 'bad';
  if (/shipped|done|live|merged|complete/.test(v)) return 'good';
  if (/^qa\b|verifying|review|smoke/.test(v)) return 'info';
  if (/building|in progress|groom|planning|ready/.test(v)) return 'busy';
  return 'plain';
}

/** `3 of 7 stories have commits · …` → `{ done: 3, total: 7 }` (live-build-view S2.2); anything else → null. */
export function progressOf(value) {
  const m = /(\d+) of (\d+) stories have commits/.exec(String(value || ''));
  if (!m) return null;
  const total = Number(m[2]);
  const done = Math.max(0, Math.min(total, Number(m[1])));
  return total > 0 ? { done, total } : null;
}

export const SPEND_BAR_WIDTH = 10;

/**
 * The Spend row's decoration (finops S2.4), parsed from the resolver's OWN words — never computed from anything else
 * (D3): `≈$38 of quote $30–55 (M) …` → a bar of 38 ÷ 55, tone good; `… % over quote …` → a full bar, tone bad (D8);
 * anything else (`no quote`, Sprint 1's line) → no bar, tone plain.
 */
export function spendOf(value) {
  const v = String(value || '');
  if (/(?:<1|\d+)% over quote \$/.test(v) || /· over quote \$/.test(v))
    return { tone: 'bad', bar: { filled: SPEND_BAR_WIDTH, width: SPEND_BAR_WIDTH } };
  const m = /^[≈≥]\$(\d+(?:\.\d+)?) of quote \$(\d+(?:\.\d+)?)–(\d+(?:\.\d+)?)/.exec(v);
  if (!m) return { tone: 'plain', bar: null };
  const actual = Number(m[1]);
  const high = Number(m[3]);
  const filled = high > 0 ? Math.max(0, Math.min(SPEND_BAR_WIDTH, Math.round((actual / high) * SPEND_BAR_WIDTH))) : 0;
  return { tone: 'good', bar: { filled, width: SPEND_BAR_WIDTH } };
}

/**
 * The view text (the resolver's lines, joined) as band rows:
 *   heading — the first line (`Currently building`, `No epic in flight — …`)
 *   field   — `  <Label>   <value>` (the resolver pads labels to 9); `main` + `meta` split the value at the
 *             resolver's four-space gap, `risk` is the meta's `risk X` word when there is one
 *   note    — a continuation line (the user story), indented under the value
 * An empty or null text gives no rows, so the band draws nothing.
 */
export function bandRowsFrom(text) {
  if (typeof text !== 'string' || !text.trim()) return [];
  return text.split('\n').map((line, i) => {
    if (i === 0) {
      const idle = /^No epic in flight/.test(line);
      return { kind: 'heading', glyph: idle ? '◇' : '◆', value: line, tone: idle ? 'plain' : 'busy' };
    }
    const field = /^ {2}([A-Z][A-Za-z]*) +(\S.*)$/.exec(line);
    if (field && field[1] in LABEL_GLYPHS) {
      const [, label, value] = field;
      const tone =
        label === 'Status' || label === 'Open'
          ? toneOf(label === 'Open' ? value.split(' · ')[1] : value)
          : label === 'Spend'
            ? spendOf(value).tone
            : 'plain';
      // `title    area · risk X`: the resolver separates the meta with four spaces; drawn dim beside it.
      const [main, ...rest] = value.split(/ {4,}/);
      const meta = rest.join('  ') || null;
      const risk = /risk (\w+)/.exec(meta || '')?.[1] || null;
      return { kind: 'field', glyph: LABEL_GLYPHS[label], label, value, main, meta, risk, tone };
    }
    return { kind: 'note', glyph: '│', value: line.trim(), tone: 'plain' };
  });
}

// ── Engines without `$.state` (fix/build-view-no-state-at-start) ────────────────────────────────────────
// The band reads the view from `$.state`, which the engine only has from some version after 2.1.278 (the CI
// pin): 2.1.278 has no `state` noun at all, so `$.state.get` throws a TypeError on every draw. A render hook
// must never throw, so every `$.state` call goes through `attempt`. It is pure — the hook passes a thunk that
// spells `$` at its own call site — so the guard is testable here, where removing it turns a test red.

/**
 * Runs `fn` and resolves its result; when it throws (synchronously, as a missing noun does) or rejects,
 * calls `onFail(err)` and resolves `fallback` instead. It never throws.
 */
export async function attempt(fn, onFail = () => {}, fallback = null) {
  try {
    return await fn();
  } catch (err) {
    try {
      onFail(err);
    } catch {
      /* a failing logger must not undo the guard */
    }
    return fallback;
  }
}

// ── The live view (live-build-view S1, D1–D5) ────────────────────────────────────────────────────────────
// Three triggers — turn.start, every Bash call, a 30 s tick — run ONE check, and the check resolves only when the key
// moved. Everything here takes its I/O as functions (`io`), built by index.tsx where each spells `$` at its own call
// site, so the whole orchestration — overlap guard included — is reachable from `node --test`.

export const TICK_MS = 30_000;
export const ONLINE_FIRST_MS = 60_000;
export const ONLINE_EVERY_MS = 300_000;
export const ONLINE_TIMEOUT_MS = 60_000; // gatherFacts' own budgets are 20 s (ls-remote) + 30 s (gh pr list)
export const GIT_TIMEOUT_MS = 2_000;
export const RESOLVE_TIMEOUT_MS = 5_000;
export const WALK_CAP = 2_000;

/**
 * `git worktree list --porcelain` → the part of the key it owns: every worktree's path, HEAD and branch (or
 * `detached`), so this checkout's HEAD + branch and every other worktree's are one string. `prunable`/`locked` notes are
 * dropped — they say nothing about what is being built. null when there is nothing (git failed).
 */
export function worktreeKeyOf(porcelain) {
  const keep = String(porcelain || '')
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => /^(worktree|HEAD|branch) /.test(l) || l === 'detached' || l === 'bare');
  return keep.length ? keep.join('|') : null;
}

/**
 * The whole key: WHICH checkout (the porcelain lists every worktree identically from any of them, so the root is what
 * tells two sessions apart), the worktrees' part, and the newest Roadmap mtime. null when git gave nothing to key on.
 */
export function keyFrom(porcelain, newestMtime, root = '') {
  const wt = worktreeKeyOf(porcelain);
  if (!wt) return null;
  return `${root}::${wt}#roadmap@${Number.isFinite(newestMtime) ? newestMtime : 'none'}`;
}

/**
 * The newest FILE mtime under `dir`, by a breadth-first walk over `list(path)` → `[{ name, kind, mtimeMs, isLink }]`
 * — `$.fs.list`'s shape, whose kinds are `file | dir | other` and whose `mtimeMs` is 0 for anything but a regular file.
 * So an edit (or a save-by-rename, which writes a new file) moves it; a DELETED doc does not, and waits for MAX_AGE_MS.
 * Stops at `cap` entries; a directory that cannot be listed (or no Roadmap/ at all) is skipped.
 */
export async function newestUnder(dir, list, cap = WALK_CAP) {
  let mtime = null;
  let entries = 0;
  const queue = [dir];
  while (queue.length) {
    const at = queue.shift();
    let items;
    try {
      items = await list(at);
    } catch {
      continue;
    }
    for (const it of items || []) {
      entries += 1;
      if (Number.isFinite(it.mtimeMs) && it.mtimeMs > 0 && (mtime === null || it.mtimeMs > mtime)) mtime = it.mtimeMs;
      if (it.kind === 'dir' && !it.isLink) queue.push(`${at}/${it.name}`);
      if (entries >= cap) return { mtime, entries, capped: true };
    }
  }
  return { mtime, entries, capped: false };
}

/** A Bash command that changes what GitHub knows about this work → one online refresh, off the turn (D3). */
export function isOnlineTrigger(command) {
  // `git -C <dir> push`, `git -c k=v push`: global options may sit between `git` and the subcommand.
  return /\bgit(?:\s+-[Cc]\s+\S+|\s+--?[\w-]+(?:=\S+)?)*\s+push\b|\bgh\s+pr\s+(?:create|ready|merge|close|reopen)\b/.test(
    String(command || '')
  );
}

// ── The drift row (D5) ───────────────────────────────────────────────────────────────────────────────────

/** `0.24.1` → [0, 24, 1]; anything that is not three dot-separated whole numbers (a pre-release tag too) → null. */
export function semverOf(v) {
  const m = /^(\d+)\.(\d+)\.(\d+)$/.exec(String(v || '').trim());
  return m ? [Number(m[1]), Number(m[2]), Number(m[3])] : null;
}

/** True only when `a` is a HIGHER release than `b`; unparseable either way → false (no row beats a wrong row). */
export function semverGt(a, b) {
  const x = semverOf(a);
  const y = semverOf(b);
  if (!x || !y) return false;
  for (let i = 0; i < 3; i++) if (x[i] !== y[i]) return x[i] > y[i];
  return false;
}

/** The band's Plugin row, or null when the installed copy is not older than the published one. */
export function versionRow(installed, published) {
  if (!semverGt(published, installed)) return null;
  return `  ${'Plugin'.padEnd(9)}${installed} installed · ${published} published — /plugin to update`;
}

/**
 * Where the marketplace clone keeps this plugin's manifest, from where the plugin is INSTALLED: Claude Code installs
 * into `…/plugins/cache/<marketplace>/<plugin>/<version>/` and clones the marketplace into
 * `…/plugins/marketplaces/<marketplace>/`, where this marketplace keeps the plugin under `plugins/<plugin>/` (its own
 * marketplace.json `source`). A `--plugin-dir` or dev load matches neither → null, and no row is drawn.
 */
export function publishedManifestPath(pluginDir) {
  const m = /^(.*\/plugins)\/cache\/([^/]+)\/([^/]+)\/[^/]+\/?$/.exec(String(pluginDir || ''));
  if (!m) return null;
  const [, base, market, plugin] = m;
  return `${base}/marketplaces/${market}/plugins/${plugin}/.claude-plugin/plugin.json`;
}

/** This plugin's own directory — the parent of hooks/ — decoded from the module URL like VENDOR_BUILD_STATE. */
export const PLUGIN_DIR = decodeURIComponent(new URL('..', import.meta.url).pathname)
  .replace(/^\/([A-Za-z]:\/)/, '$1')
  .replace(/\/$/, '');

/** `plugin.json` text → its version, or null. */
export function versionOf(text) {
  try {
    const v = JSON.parse(String(text)).version;
    return typeof v === 'string' ? v : null;
  } catch {
    return null;
  }
}

/** The view as drawn: the resolver's text, plus the mod's own Plugin row when there is a view to put it under. */
export function composeView(text, plugin = null) {
  if (typeof text !== 'string' || !text) return null;
  return plugin ? `${text}\n${plugin}` : text;
}

/**
 * The live view's engine. `io`:
 *   run(argv, { timeoutMs }) → { exitCode, stdout }   — $.process.run
 *   list(path) → entries                                — $.fs.list
 *   getCached(root) / setCached(root, entry)            — $.store, ONE SLOT PER CHECKOUT ROOT (the store is shared by
 *                                                         every session of the plugin; a slot per root keeps two
 *                                                         sessions in two worktrees from serving each other's view)
 *   show(text | null)                                   — $.state.set of the band
 *   log(msg)                                            — $.ui.log
 *   now() → ms
 * `check(reason)` returns what it did: 'busy' (another check is running — D1, none overlap — and it will run ONE more
 * pass when it finishes, so the trigger is deferred, never dropped), 'no-repo', 'cached', 'resolved', 'failed'.
 * `invalidate()` makes the next pass resolve whatever the key says (a new snapshot or usage figure moves no key).
 * `refreshOnline()` runs the resolver online — which rewrites the facts snapshot — then a forced check (D3).
 */
export const MAX_RERUNS = 2; // a burst of triggers during one check collapses into at most this many extra passes

export function createViewer(io, { buildState = VENDOR_BUILD_STATE } = {}) {
  let checking = false;
  let rerun = false; // a trigger arrived while a check ran
  let forceNext = false; // invalidate(): the next pass resolves even on an unchanged key
  let onlineBusy = false;
  let warnedOffline = false;
  let shown; // undefined until the first show, so the first check always draws
  let plugin = null;

  async function pass(reason) {
    const started = io.now();
    let did = 'cached';
    let entries = 0;
    try {
      const root = await viewer.locate();
      if (!root) {
        did = 'no-repo';
        await viewer.show(null);
        return did;
      }
      const wt = await io.run(['git', '-C', root, 'worktree', 'list', '--porcelain'], { timeoutMs: GIT_TIMEOUT_MS });
      const walk = await newestUnder(`${root}/Roadmap`, io.list);
      entries = walk.entries;
      const key = keyFrom(wt.exitCode === 0 ? wt.stdout : '', walk.mtime, root);
      const force = forceNext;
      forceNext = false;
      const cached = force ? null : await io.getCached(root);
      if (!force && !shouldRefresh(cached, key, io.now())) {
        await viewer.show(cached.text || null);
        return did;
      }
      const run = await io.run(buildStateArgv(root, buildState), { timeoutMs: RESOLVE_TIMEOUT_MS });
      const text = statusTextFrom(run.stdout, run.exitCode);
      did = 'resolved';
      await viewer.show(text);
      // Drawn first: a cache write that fails (the plugin's one $.store file is capped, and every checkout root keeps a
      // slot) must cost a re-resolve next time, never the view itself (#240 review, round 2).
      try {
        await io.setCached(root, { key, at: io.now(), text });
      } catch (err) {
        io.log(`build view: could not cache the view (${String(err)})`);
      }
      return did;
    } catch (err) {
      did = 'failed';
      io.log(`build view: ${String(err)}`);
      try {
        await viewer.show(null);
      } catch {
        /* an engine without $.state — logged by the band itself */
      }
      return did;
    } finally {
      viewer.lastCheck = { reason, did, ms: io.now() - started, entries };
      io.log(`build view: ${reason} check ${did} in ${viewer.lastCheck.ms} ms (${entries} Roadmap entries)`);
    }
  }

  const viewer = {
    root: null,
    lastCheck: null, // { reason, did, ms, entries } — logged, and what the PR's cost figure is read from
    setPluginRow(row) {
      plugin = row;
    },
    invalidate() {
      forceNext = true;
    },
    async show(text) {
      const next = composeView(text, plugin);
      if (next === shown) return;
      shown = next;
      await io.show(next);
    },
    async locate() {
      if (viewer.root) return viewer.root;
      const head = await io.run(['git', 'rev-parse', 'HEAD', '--abbrev-ref', 'HEAD', '--show-toplevel'], {
        timeoutMs: GIT_TIMEOUT_MS,
      });
      viewer.root = repoFactsFrom(head.stdout, head.exitCode).root;
      return viewer.root;
    },
    async check(reason = 'turn') {
      if (checking) {
        rerun = true;
        return 'busy';
      }
      checking = true;
      try {
        let did = await pass(reason);
        for (let n = 0; rerun && n < MAX_RERUNS; n++) {
          rerun = false;
          const again = await pass(`${reason}+deferred`);
          if (did !== 'resolved') did = again; // a resolve in any pass is what the caller wants to know
        }
        // A trigger landing during the LAST deferred pass is dropped here; the next tick (≤ 30 s) picks it up, and an
        // invalidate() survives in forceNext either way.
        rerun = false;
        return did;
      } finally {
        checking = false;
      }
    },
    async refreshOnline(reason = 'timer') {
      if (onlineBusy) return 'busy';
      onlineBusy = true;
      try {
        const root = await viewer.locate();
        if (!root) return 'no-repo';
        // The run's own lines are not drawn: the forced offline pass below reads the snapshot this run just wrote,
        // through the same path as every other check — one way a view reaches the band (amended D3).
        const run = await io.run(buildStateArgv(root, buildState, { offline: false }), { timeoutMs: ONLINE_TIMEOUT_MS });
        let mode = null;
        try {
          mode = JSON.parse(String(run.stdout)).facts_mode ?? null;
        } catch {
          /* a failed run says nothing — the snapshot stays as it was */
        }
        if (mode !== 'live' && !warnedOffline) {
          warnedOffline = true;
          io.log(`build view: online refresh (${reason}) got no live facts (${mode ?? `exit ${run.exitCode}`}) — no gh, or gh failed; keeping the last snapshot`);
        }
        viewer.invalidate();
        await viewer.check(`online:${reason}`);
        return mode === 'live' ? 'live' : 'offline';
      } catch (err) {
        io.log(`build view: online refresh: ${String(err)}`);
        return 'failed';
      } finally {
        onlineBusy = false;
      }
    },
  };
  return viewer;
}

// ── /build <slug> — the kickoff's one home (live-build-view S2.4, D12) ───────────────────────────────────────────────
// The mod runs the BUNDLED kickoff generator (the groom skill's own copy, never one the open repo supplies — the same
// rule as the resolver) and puts its output in the prompt box; the person presses enter. Nothing is saved anywhere:
// the epic docs are the state, and the kickoff is regenerated from them every time.
export const VENDOR_EMIT_KICKOFF = decodeURIComponent(
  new URL('../skills/groom/emit-epic-kickoff.mjs', import.meta.url).pathname
).replace(/^\/([A-Za-z]:\/)/, '$1');
export const KICKOFF_TIMEOUT_MS = 10_000;

/** An epic slug as the Roadmap writes them. Anything else (empty, a flag, a path) gets the list instead. */
export function isEpicSlug(arg) {
  return /^[a-z0-9][a-z0-9-]*$/.test(String(arg || '').trim());
}

/** The generator's argv: the kickoff for `slug`, or the list of startable epics when `slug` is null. */
export function kickoffArgv(root, slug, script = VENDOR_EMIT_KICKOFF) {
  return slug
    ? ['node', script, '--epic', slug, '--repo-root', root || '.']
    : ['node', script, '--list', '--repo-root', root || '.'];
}

/** What `/build` prints when it fills nothing: the list, headed by why. */
export function buildListText(reason, listStdout) {
  const list = String(listStdout || '').trim() || '(could not list the epics)';
  return `${reason}\nUsage: /build <epic-slug> — the epics a kickoff can start:\n${list}`;
}
