// build-view.mjs — the build view mod's PURE half (build-visualization-claude-mods S4, D3).
//
// The hook module (./index.ts) may only call `$.noun.event(...)` at a call site — the runtime rejects a
// module that passes `$` around — so everything that can be decided without `$` lives here, where
// `node --test` can reach it. The mod itself is then: read the key, ask this module whether to refresh,
// run `scripts/build-state.mjs`, hand the text to `$.ui.status`. No markdown parsing, no logic of its own.

/**
 * What `git rev-parse HEAD --abbrev-ref HEAD --show-toplevel` says: the cache key (branch@sha) and the
 * repository ROOT. The root matters — a session started in a subdirectory would otherwise run
 * `scripts/build-state.mjs` relative to that subdirectory and never find it.
 */
export function repoFactsFrom(stdout, exitCode = 0) {
  if (exitCode !== 0) return { key: null, root: null };
  const [sha = '', branch = '', root = ''] = String(stdout || '')
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean);
  return { key: sha && branch ? `${branch}@${sha}` : null, root: root || null };
}

// A Roadmap/ write changes no git ref, so a key alone would serve a stale view until the next commit.
// Stat-ing the whole tree every turn is the cost the cache exists to avoid (860+ docs in the largest
// consumer), so a refresh also happens when the cached view is older than this. A doc edit therefore
// shows up within 15s; a branch change or a commit shows up immediately.
export const MAX_AGE_MS = 15_000;

/**
 * Refresh when there is no usable entry, the branch/HEAD moved, or the view aged out.
 *
 * A FAILED resolve is a usable entry: `text: null` is cached like any other answer, so a project that
 * has the plugin but not `scripts/build-state.mjs` re-tries once every MAX_AGE_MS instead of spawning a
 * doomed `node` on every single turn (the fresh reviewer's finding on #32). `key: null` — no git, or a
 * `git rev-parse` that failed — is the one case with nothing to key on, and it refreshes every turn by
 * design: there is no way to know that anything is still true.
 */
export function shouldRefresh(cached, key, now = Date.now()) {
  if (!key) return true;
  if (!cached || cached.key !== key) return true;
  const resolved = typeof cached.text === 'string' || cached.text === null;
  if (!resolved || !('text' in cached)) return true;
  return !(Number.isFinite(cached.at) && now - cached.at < MAX_AGE_MS);
}

/**
 * The status text for one `build-state.mjs --json` run: its OWN `lines`, joined — never re-derived here
 * (D3). A non-zero exit, unparseable output or a missing `lines` array renders nothing at all: a build
 * view that invents a line is worse than no build view.
 */
export function statusTextFrom(stdout, exitCode = 0) {
  if (exitCode !== 0) return null;
  try {
    const state = JSON.parse(String(stdout));
    return Array.isArray(state.lines) && state.lines.length ? state.lines.join('\n') : null;
  } catch {
    return null;
  }
}

/**
 * The resolver bundled beside this file (`hooks/vendor/`, generated by skills/scripts/render-hook-vendor.mjs).
 * Located from this module's own URL — probed live in a function-hooks module (distribute-what-we-use S2.2):
 * `import.meta.url` is the plugin's installed directory, and `$.process.run` can execute a file there.
 * Decoded by hand so this file keeps its no-import shape; the drive-letter strip covers a Windows install.
 */
export const VENDOR_BUILD_STATE = decodeURIComponent(
  new URL('./vendor/build-state.mjs', import.meta.url).pathname
).replace(/^\/([A-Za-z]:\/)/, '$1');

/**
 * The command the hook runs. ALWAYS the bundled resolver — never `<repo>/scripts/build-state.mjs`, whether
 * or not the open repo has one (D5). The hook is automatic: it runs on every turn in whatever repo the user
 * opens, so it must never execute a file that repo supplies. The repo is only ever READ, via `--repo-root`.
 */
export function buildStateArgv(root, script = VENDOR_BUILD_STATE) {
  return ['node', script, '--json', '--offline', '--repo-root', root || '.'];
}
